[target.'cfg(target_arch = "x86_64")']
rustflags = "-C target-feature=+avx2"

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.7"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.7"]
